# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 240)
        MainWindow.setMinimumSize(QtCore.QSize(300, 240))
        MainWindow.setMaximumSize(QtCore.QSize(300, 240))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.easyButton = QtWidgets.QPushButton(self.centralwidget)
        self.easyButton.setGeometry(QtCore.QRect(130, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.easyButton.setFont(font)
        self.easyButton.setObjectName("easyButton")
        self.proButton = QtWidgets.QPushButton(self.centralwidget)
        self.proButton.setGeometry(QtCore.QRect(130, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.proButton.setFont(font)
        self.proButton.setObjectName("proButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 60, 67, 16))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.validButton = QtWidgets.QPushButton(self.centralwidget)
        self.validButton.setGeometry(QtCore.QRect(130, 160, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.validButton.setFont(font)
        self.validButton.setObjectName("validButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 130, 201, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 170, 67, 16))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "模式选择"))
        self.easyButton.setText(_translate("MainWindow", "简单模式"))
        self.proButton.setText(_translate("MainWindow", "专业模式"))
        self.label.setText(_translate("MainWindow", "数据处理"))
        self.validButton.setText(_translate("MainWindow", "检测模式"))
        self.label_2.setText(_translate("MainWindow", "数据检测"))
