# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProWindow(object):
    def setupUi(self, ProWindow):
        ProWindow.setObjectName("ProWindow")
        ProWindow.resize(452, 500)
        ProWindow.setMinimumSize(QtCore.QSize(452, 500))
        ProWindow.setMaximumSize(QtCore.QSize(452, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Pictures/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ProWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ProWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.process_button = QtWidgets.QPushButton(self.centralwidget)
        self.process_button.setGeometry(QtCore.QRect(290, 260, 100, 60))
        self.process_button.setMinimumSize(QtCore.QSize(100, 60))
        self.process_button.setMaximumSize(QtCore.QSize(100, 60))
        self.process_button.setObjectName("process_button")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(60, 200, 341, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(290, 80, 102, 88))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_file_button = QtWidgets.QPushButton(self.layoutWidget)
        self.load_file_button.setMinimumSize(QtCore.QSize(100, 40))
        self.load_file_button.setMaximumSize(QtCore.QSize(100, 40))
        self.load_file_button.setObjectName("load_file_button")
        self.verticalLayout.addWidget(self.load_file_button)
        self.load_dir_button = QtWidgets.QPushButton(self.layoutWidget)
        self.load_dir_button.setMinimumSize(QtCore.QSize(100, 40))
        self.load_dir_button.setMaximumSize(QtCore.QSize(100, 40))
        self.load_dir_button.setObjectName("load_dir_button")
        self.verticalLayout.addWidget(self.load_dir_button)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(60, 350, 341, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 400, 208, 63))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.out_amount = QtWidgets.QSpinBox(self.layoutWidget1)
        self.out_amount.setMinimumSize(QtCore.QSize(70, 0))
        self.out_amount.setMaximumSize(QtCore.QSize(70, 16777215))
        self.out_amount.setObjectName("out_amount")
        self.gridLayout_2.addWidget(self.out_amount, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.multiple_sv_button = QtWidgets.QRadioButton(self.layoutWidget1)
        self.multiple_sv_button.setMinimumSize(QtCore.QSize(0, 0))
        self.multiple_sv_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.multiple_sv_button.setObjectName("multiple_sv_button")
        self.save_mode_BG = QtWidgets.QButtonGroup(ProWindow)
        self.save_mode_BG.setObjectName("save_mode_BG")
        self.save_mode_BG.addButton(self.multiple_sv_button)
        self.gridLayout_2.addWidget(self.multiple_sv_button, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.single_sv_button = QtWidgets.QRadioButton(self.layoutWidget1)
        self.single_sv_button.setMinimumSize(QtCore.QSize(0, 0))
        self.single_sv_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.single_sv_button.setObjectName("single_sv_button")
        self.save_mode_BG.addButton(self.single_sv_button)
        self.gridLayout_2.addWidget(self.single_sv_button, 0, 0, 1, 1)
        self.load_label = QtWidgets.QLabel(self.centralwidget)
        self.load_label.setGeometry(QtCore.QRect(60, 40, 341, 20))
        self.load_label.setObjectName("load_label")
        self.save_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_file_button.setGeometry(QtCore.QRect(290, 400, 100, 60))
        self.save_file_button.setMinimumSize(QtCore.QSize(100, 60))
        self.save_file_button.setMaximumSize(QtCore.QSize(100, 60))
        self.save_file_button.setObjectName("save_file_button")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(60, 30, 341, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(70, 70, 210, 122))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.renishaw_select_button = QtWidgets.QRadioButton(self.layoutWidget2)
        self.renishaw_select_button.setObjectName("renishaw_select_button")
        self.load_type_BG = QtWidgets.QButtonGroup(ProWindow)
        self.load_type_BG.setObjectName("load_type_BG")
        self.load_type_BG.addButton(self.renishaw_select_button)
        self.gridLayout.addWidget(self.renishaw_select_button, 0, 0, 1, 1)
        self.ezraman_select_button = QtWidgets.QRadioButton(self.layoutWidget2)
        self.ezraman_select_button.setObjectName("ezraman_select_button")
        self.load_type_BG.addButton(self.ezraman_select_button)
        self.gridLayout.addWidget(self.ezraman_select_button, 0, 1, 1, 1)
        self.iramanplus_select_button = QtWidgets.QRadioButton(self.layoutWidget2)
        self.iramanplus_select_button.setObjectName("iramanplus_select_button")
        self.load_type_BG.addButton(self.iramanplus_select_button)
        self.gridLayout.addWidget(self.iramanplus_select_button, 1, 0, 1, 1)
        self.other_select_button = QtWidgets.QRadioButton(self.layoutWidget2)
        self.other_select_button.setObjectName("other_select_button")
        self.load_type_BG.addButton(self.other_select_button)
        self.gridLayout.addWidget(self.other_select_button, 1, 1, 1, 1)
        self.header_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.header_line.setObjectName("header_line")
        self.gridLayout.addWidget(self.header_line, 2, 0, 1, 1)
        self.sep_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.sep_line.setObjectName("sep_line")
        self.gridLayout.addWidget(self.sep_line, 2, 1, 1, 1)
        self.shift_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.shift_line.setObjectName("shift_line")
        self.gridLayout.addWidget(self.shift_line, 3, 0, 1, 1)
        self.spectrum_line = QtWidgets.QLineEdit(self.layoutWidget2)
        self.spectrum_line.setObjectName("spectrum_line")
        self.gridLayout.addWidget(self.spectrum_line, 3, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(70, 250, 181, 101))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.method1_button = QtWidgets.QRadioButton(self.layoutWidget3)
        self.method1_button.setMinimumSize(QtCore.QSize(0, 0))
        self.method1_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.method1_button.setObjectName("method1_button")
        self.classify_mode_BG = QtWidgets.QButtonGroup(ProWindow)
        self.classify_mode_BG.setObjectName("classify_mode_BG")
        self.classify_mode_BG.addButton(self.method1_button)
        self.gridLayout_3.addWidget(self.method1_button, 0, 0, 1, 1)
        self.method2_button = QtWidgets.QRadioButton(self.layoutWidget3)
        self.method2_button.setMinimumSize(QtCore.QSize(0, 0))
        self.method2_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.method2_button.setObjectName("method2_button")
        self.classify_mode_BG.addButton(self.method2_button)
        self.gridLayout_3.addWidget(self.method2_button, 0, 1, 1, 1)
        self.method3_button = QtWidgets.QRadioButton(self.layoutWidget3)
        self.method3_button.setMinimumSize(QtCore.QSize(0, 0))
        self.method3_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.method3_button.setObjectName("method3_button")
        self.classify_mode_BG.addButton(self.method3_button)
        self.gridLayout_3.addWidget(self.method3_button, 1, 0, 1, 1)
        self.no_classify_button = QtWidgets.QRadioButton(self.layoutWidget3)
        self.no_classify_button.setMinimumSize(QtCore.QSize(0, 0))
        self.no_classify_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.no_classify_button.setObjectName("no_classify_button")
        self.classify_mode_BG.addButton(self.no_classify_button)
        self.gridLayout_3.addWidget(self.no_classify_button, 1, 1, 1, 1)
        self.bs_remove_button = QtWidgets.QRadioButton(self.layoutWidget3)
        self.bs_remove_button.setMinimumSize(QtCore.QSize(0, 0))
        self.bs_remove_button.setObjectName("bs_remove_button")
        self.gridLayout_3.addWidget(self.bs_remove_button, 2, 0, 1, 1)
        self.peak_location = QtWidgets.QLineEdit(self.layoutWidget3)
        self.peak_location.setMinimumSize(QtCore.QSize(0, 0))
        self.peak_location.setMaximumSize(QtCore.QSize(70, 16777215))
        self.peak_location.setObjectName("peak_location")
        self.gridLayout_3.addWidget(self.peak_location, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.process_label = QtWidgets.QLabel(self.centralwidget)
        self.process_label.setGeometry(QtCore.QRect(50, 220, 341, 20))
        self.process_label.setObjectName("process_label")
        self.save_label = QtWidgets.QLabel(self.centralwidget)
        self.save_label.setGeometry(QtCore.QRect(50, 370, 341, 20))
        self.save_label.setObjectName("save_label")
        ProWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProWindow)
        QtCore.QMetaObject.connectSlotsByName(ProWindow)

    def retranslateUi(self, ProWindow):
        _translate = QtCore.QCoreApplication.translate
        ProWindow.setWindowTitle(_translate("ProWindow", "专业模式"))
        self.process_button.setText(_translate("ProWindow", "数据处理"))
        self.load_file_button.setText(_translate("ProWindow", "加载文件"))
        self.load_dir_button.setText(_translate("ProWindow", "加载文件夹"))
        self.multiple_sv_button.setText(_translate("ProWindow", "多文件保存"))
        self.label_2.setText(_translate("ProWindow", "<html><head/><body><p align=\"center\">输出光谱数量</p></body></html>"))
        self.single_sv_button.setText(_translate("ProWindow", "单文件保存"))
        self.load_label.setText(_translate("ProWindow", "<html><head/><body><p align=\"center\">等待加载</p></body></html>"))
        self.save_file_button.setText(_translate("ProWindow", "保存"))
        self.renishaw_select_button.setText(_translate("ProWindow", "Renishaw"))
        self.ezraman_select_button.setText(_translate("ProWindow", "Ez Raman"))
        self.iramanplus_select_button.setText(_translate("ProWindow", "i Raman Plus"))
        self.other_select_button.setText(_translate("ProWindow", "自定义"))
        self.header_line.setText(_translate("ProWindow", "表头"))
        self.sep_line.setText(_translate("ProWindow", "分隔符"))
        self.shift_line.setText(_translate("ProWindow", "位移坐标"))
        self.spectrum_line.setText(_translate("ProWindow", "光谱坐标"))
        self.method1_button.setText(_translate("ProWindow", "方法1"))
        self.method2_button.setText(_translate("ProWindow", "方法2"))
        self.method3_button.setText(_translate("ProWindow", "方法3"))
        self.no_classify_button.setText(_translate("ProWindow", "不进行筛选"))
        self.bs_remove_button.setText(_translate("ProWindow", "去基线"))
        self.peak_location.setText(_translate("ProWindow", "筛选峰位"))
        self.process_label.setText(_translate("ProWindow", "<html><head/><body><p align=\"center\">等待处理</p></body></html>"))
        self.save_label.setText(_translate("ProWindow", "<html><head/><body><p align=\"center\">等待保存</p></body></html>"))
